# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0960a43f3cb5e3882b9b324625f417c9bb56e3a644787c8f995081705cddab25d3cce0fd233742904acddf0d7a848458d5b8b78522fc69142f9aa37e3fbe123

test:
  secret_key_base: 5a8a509762b351da5f207d77fcef426287180a2b8a1fceb63a0f7c2d607fcd4f3ca7f763f6507703eca56b83756fe10ffee9739675cf7f8120b9afde394231c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
